[package]

name = "wol"
version = "0.0.1"
authors = ["Dave Lancaster <lancaster.dave@gmail.com>"]

[[bin]]

name = "wol"
path = "src/wol.rs"

[dependencies]


getopts = "0.1.4"
regex = "0.1.10"