[package]

name = "wol"
version = "0.0.1"
authors = ["Dave Lancaster <lancaster.dave@gmail.com>"]

[[bin]]

name = "wol"
path = "src/main.rs"

[dependencies]


getopts = "0.2.3"
regex = "0.1.14"